ruby '2.1.5'
source 'https://rubygems.org'

gem 'bootstrap-sass',           '3.3.1.0'
gem 'bootswatch-rails',         '3.2.4'
gem 'coffee-rails',             '4.1.0'
gem 'font-awesome-sass',        '4.2.2'
gem 'jbuilder',                 '2.2.5'
gem 'jquery-rails',             '4.0.0'
gem 'jquery-turbolinks',        '2.1.0'
gem 'omniauth',                 '1.2.2'
gem 'omniauth-facebook',        '2.0.0'
gem 'pg',                       '0.17.1'
gem 'rails',                    '4.2.0'
gem 'sass-rails',               '4.0.5'
gem 'simple_form',              '3.1.0'
gem 'turbolinks',               '2.5.3'
gem 'uglifier',                 '2.6.0'

group :development do
  gem 'annotate',               '2.6.5'
  gem 'byebug',                 '3.5.1'
  gem 'rspec-rails',            '3.1.0'
  gem 'web-console',            '2.0.0'
end
