development:   
  adapter: postgresql
  encoding: unicode
  database: classes_with_me_development
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: classes_with_me_production
  pool: 5
  username: ...
  password: ...