development:   
  adapter: postgresql
  encoding: unicode
  database: classes-with-me_development
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ...
  pool: 5
  username: ...
  password: ...